examples/cpp/loading_sparse_qp.cpp
examples/cpp/solve_without_api.cpp
examples/cpp/solve_without_api_and_option.cpp
examples/cpp/update_sparse_qp.cpp
test/src/sparse_qp.cpp
test/src/sparse_qp_solve.cpp
test/src/sparse_qp_wrapper.cpp
test/src/sparse_ruiz_equilibration.cpp

Hi,
On a standard ubuntu 20.04, with gcc 9.4 and eigen 3.3.7, eigen has a `std::cerr` somewhere and compilation raise some occurences of : 
```
In file included from /usr/include/eigen3/unsupported/Eigen/IterativeSolvers:29,
from ../include/proxsuite/proxqp/sparse/views.hpp:21,
from ../include/proxsuite/proxqp/sparse/solver.hpp:20,
from ../include/proxsuite/proxqp/sparse/wrapper.hpp:12,
from ../test/src/sparse_qp.cpp:4:
/usr/include/eigen3/unsupported/Eigen/src/IterativeSolvers/ConstrainedConjGrad.h: In function ‘void Eigen::internal::constrained_cg(const TMatrix&, const CMatrix&, VectorX&, const VectorB&, const VectorF&, Eigen::IterationController&)’:
/usr/include/eigen3/unsupported/Eigen/src/IterativeSolvers/ConstrainedConjGrad.h:162:51: error: ‘cerr’ is not a member of ‘std’
162 | …
```

add missing includes

---

include/proxsuite/proxqp/dense/preconditioner/ruiz.hpp

While debugging the unittests from cvxpy, we added these changes here to make our API more robust and easy to maintain with @Bambade.
- allocate delta the same way as done in the sparse counterpart
- make sure that 0 cols do not cause any problems

Fix preconditioner

---

.github/workflows/release.yml
pyproject.toml

Enables `pip install proxsuite` for python >=3.7, instead python >= 3.8.

Support python 3.7 for proxsuite wheels

---

.github/workflows/release.yml

Currently, additional wheels were built ([workflow](https://github.com/Simple-Robotics/proxsuite/actions/runs/3130836562/jobs/5086549476#step:6:19)), and it was changing over time. This leads to errors when uploading them to pypi. PR fixes this problem.

CI/release: fix uploading proxsuite wheels only

---

README.md
doc/1-Overview.md
examples/cpp/benchmark_dense_qp.cpp

With this PR, we add and document a benchmark example that shows how a speed-up can be achieved by using vectorization with the corresponding compile flags.
This is following #45.

benchmark: document speed up by vectorization

---

.github/workflows/ci-osx-arm64-conda.yml
bindings/python/CMakeLists.txt
bindings/python/proxsuite/__init__.py
include/proxsuite/linalg/dense/core.hpp

As requested in #41, this PR 
- do not use instructionset for python bindings
- add CI workflow for ARM64 on self-hosted runner (M1)

Support ARM64 architecture

---

.github/workflows/release.yml

This PR builds and uploads wheels for macos ARM64. 
It uses the self-hosted M1 runner and a conda environment with the corresponding python version. An additional step is necessary, to turn off vectorization in the `pyproject.toml`.
The additional artifacts are:
```
proxsuite-<version>-cp38-cp38-macosx_12_0_arm64.whl
proxsuite-<version>-cp39-cp39-macosx_12_0_arm64.whl
proxsuite-<version>-cp310-cp310-macosx_12_0_arm64.whl
```

release: wheels for macos arm64

---

include/proxsuite/proxqp/dense/helpers.hpp
include/proxsuite/proxqp/dense/solver.hpp
include/proxsuite/proxqp/dense/workspace.hpp
include/proxsuite/proxqp/sparse/solver.hpp

As seen in #46, very large bounds on the inequality constraints (in this case 1e20) cause strange behavior in the solver. After discussing with @Bambade, this PR fixes the issue.

Fix epsilon relative stopping criteria

---

include/proxsuite/linalg/veg/internal/macros.hpp
include/proxsuite/proxqp/dense/wrapper.hpp
include/proxsuite/proxqp/sparse/wrapper.hpp
test/src/dense_qp_wrapper.cpp
test/src/sparse_qp_wrapper.cpp

handle the case that the dense/sparse wrapper has empty matrices as input (instead of `std::nullopt`) to the `init` method that do not have the corresponding dimension of the qp problem but 0.

Handle empty inputs

---

include/proxsuite/proxqp/dense/solver.hpp

Reset was missing. If run with verbose `true` this caused that the `objVal` was half of what it should have been, found with @Bambade.

Fix calculation of objection function value

---

doc/5-installation.md

as pointed out in #57, the link in our doc is pointing to matio-cpp but we are actually using matio, see [here](https://github.com/Simple-Robotics/proxsuite/blob/e97f76605da03ae624927b3615cb2540144bbacc/cmake-external/FindMatio.cmake#L32) and [here](https://github.com/Simple-Robotics/proxsuite/blob/e97f76605da03ae624927b3615cb2540144bbacc/test/include/maros_meszaros.hpp#L2)

Doc: matio link

---

include/proxsuite/proxqp/sparse/solver.hpp

proposed by @Bambade , necessary to solve large sparse problems like the HUESTIS problem from maros meszaros.

sparse/solver: use refactorize for matrix free solver

---

.github/workflows/ci-linux-osx-win-conda.yml
bindings/python/src/expose-all.cpp
include/proxsuite/fwd.hpp
include/proxsuite/helpers/common.hpp
include/proxsuite/linalg/sparse/update.hpp
include/proxsuite/linalg/veg/internal/narrow.hpp
include/proxsuite/linalg/veg/memory/alloc.hpp
include/proxsuite/linalg/veg/memory/dynamic_stack.hpp
include/proxsuite/optional.hpp
include/proxsuite/proxqp/sparse/utils.hpp
test/doctest/doctest.hpp

- also fix the [[MAYBE_UNSUED]] problem which is introduced in c++17
with this PR, including also the changes done in #78, I can compile the proxsuite library enforcing c++14.

C++14 compliant implementation of aligned_alloc

---

.github/workflows/ci-linux-osx-win-conda.yml
CMakeLists.txt
include/proxsuite/helpers/instruction-set.hpp
include/proxsuite/helpers/optional.hpp
include/proxsuite/linalg/veg/memory/alloc.hpp
include/proxsuite/proxqp/dense/wrapper.hpp

This PR adds one additonal pipeline running the macos workflow with std=c++14. In the `CMakeLists.txt` file, we check now that the defined cxx standard is at least 14, but our default will still be 17 if user is not setting it.

CI for c++14 compatibility

---

.github/workflows/ci-linux-osx-win-conda.yml
CMakeLists.txt
include/proxsuite/fwd.hpp
include/proxsuite/proxqp/dense/solver.hpp

after #91 , seems useful to have an option to quickly check. The macOS debug pipeline was adapted to use the `CHECK_RUNTIME_MALLOC` option. For now, this is just introduced in the dense backend.

Additional option to check eigen runtime malloc

---

include/proxsuite/proxqp/dense/solver.hpp
include/proxsuite/proxqp/dense/utils.hpp
include/proxsuite/proxqp/results.hpp
include/proxsuite/proxqp/sparse/solver.hpp
include/proxsuite/proxqp/sparse/utils.hpp

Add duality gap measure to dense and sparse backends:
- the measure is a-dimensional (i.e., the duality gap is divided by the max of primal and dual dimensions),
- it is integrated as a relative stopping criterion,
- it is unit-tested in c++ and python.

Add duality gap measure

---

.github/workflows/ci-linux-osx-win-conda.yml
.github/workflows/release.yml

- currently we check for runtime memory allocations in this one specific pipeline
- we still observe a few during the dense solve, but we don't want to PRs to be marked as failed, it's a way to keep track of mem allocs but no critical failure

Allow macOS Debug pipeline to fail -> checking for memory alloc

---

bindings/python/proxsuite/__init__.py

Currently, we are not importing the instructionset if `platform.processor()` returns an empty string, like it was observed in #119.

fix instructionset import

---

README.md
examples/cpp/first_example.cpp
examples/cpp/first_example_dense.cpp
examples/cpp/first_example_sparse.cpp

After discussing with @lmontaut, we think it could be helpful for users getting started with proxqp in c++ to have a very simple example showing how you use Eigen to setup a small problem with your own values. All our examples/unittests either use a function to generate a random qp or read in a mat file.
This simple first example can then also be used in the readme section explaining how to compile a program.

Add simple cpp example

---

bindings/python/CMakeLists.txt

before https://github.com/jrl-umi3218/jrl-cmakemodules/pull/569, the [path to additional modules](https://github.com/Simple-Robotics/proxsuite/blob/main/test/CMakeLists.txt#L55) specified in the test was not properly set on windows. As a results, the unittest could not import the package from this path, so it imported it from the corresponding (conda) env, we had to install the package before.
Now, the path is properly set, so the unittest is importing the package locally from the build folder, but the folder structure impedes a correct import. We have :
`build/bindings/python/proxsuite/__init__.py`
but then the modules, like instructionset/proxsuite are in 
`build/bindings/python/proxsuite/Release/instructionset`
This PR removes the intermediate per-configurations appended subfolder.

cmake/python: update library output paths

---

bindings/python/CMakeLists.txt
include/proxsuite/serialization/eigen.hpp
test/CMakeLists.txt
test/src/serialization.cpp

leading to problems otherwise: https://github.com/Simple-Robotics/proxsuite/actions/runs/3750814032/jobs/6371012995#step:5:123 (here we use eigen [3.3.7](https://github.com/Simple-Robotics/proxsuite/actions/runs/3750814032/jobs/6371012995#step:3:57)) although I don't really understand why after checking eigen 3.3 should already include [transposeInPlace](https://eigen.tuxfamily.org/dox-3.3/classEigen_1_1DenseBase.html#ac501bd942994af7a95d95bee7a16ad2a).

transposeInPlace only if eigen >= 3.4.0

---

.github/workflows/ci-linux-ros.yml
examples/cpp/first_example_sparse.cpp
test/src/sparse_qp_wrapper.cpp

Follow-up to #158:
1. Enables Debug and Release configurations for the ROS-CI
2. Fixes warnings highlighted during CI: unused variables and narrowing conversion

ROS-CI: Debug and Release builds, fix warnings

---

include/proxsuite/linalg/dense/ldlt.hpp

In order to interface with the backend's `Lldt` class we need to be able to grab the permutation matrices on a `const Ldlt` pointer or reference. This PR fixes constness on the getters.

linalg/ldlt : mark p() and pt() permutation matrix getters const

---

.github/workflows/ci-linux-ros.yml
package.xml

I added libsimde-dev into package.xml.
Also I created [a PR](https://github.com/ros/rosdistro/pull/36216) to add libsimde-dev into rosdistro.

feat: enable simde in package.xml

---

.github/workflows/ci-linux-ros.yml

To check if we could move to packaging/vendoring

[CI] ROS: Activate prerelease

---

.github/workflows/release.yml

Extend our current release workflow to also build wheels for `windows-latest` and `windows-2019`. This is now possible due to improvements we have done together with @nim65s on https://github.com/cmake-wheel/cmeel.
ref #179

CI: pip wheels on windows

---

examples/cpp/benchmark_dense_qp.cpp

after setting `compute_timings = false` by default, we have to manually turn it on when we want to compute them, see #190.

set compute_timings = true

---

.github/workflows/release-linux.yml
.github/workflows/release-osx-win.yml
bindings/python/CMakeLists.txt
pyproject.toml

use another release workflow for Linux wheels to support `manylinux_2_17` instead of `manylinux_2_35`. This is possible using `cibuildwheel`, thanks to @nim65s who released `cmeel-simde` today. This should solve the problems observed in #194.

ci/linux: fix linux wheel compatibility

---

.github/workflows/release-linux.yml

The step to upload the artifacts to pypi expects the wheels in a folder called `dist`. I uploaded the ubuntu wheels for `v0.3.5` manually to pypi after the workflow [failed](https://github.com/Simple-Robotics/proxsuite/actions/runs/4346463866/jobs/7593621507#step:6:20) due to a naming mismatch. This here will fix it for future releases.

ci/linux-wheels: fix naming for artifacts

---

.github/workflows/release-linux.yml

pip wheels for aarch64

---

CMakeLists.txt

As-is, at least on CMake 3.25, `set(PROXSUITE_AS_SUBPROJECT)` does not
cause it to evaluate as true in the below tests
Topic: proxsuite-as-subproject

Define PROXSUITE_AS_SUBPROJECT as ON

---

package.xml

ROS2 Iron is released on Ubuntu Jammy which has simde available. Adding the conditional dependency fixes the builds

Set simde dependency for ROS2 Iron as well

---

include/proxsuite/proxqp/dense/solver.hpp

Reuse linear algebra operations (which involves matrix vector products) made during iterative refinement for the updates done after the exact line-search.
Unit tested in c++ and python.

optimize dense iterative refinement

---

bindings/python/src/expose-settings.hpp
doc/2-PROXQP_API/2-ProxQP_api.md
include/proxsuite/proxqp/dense/helpers.hpp
include/proxsuite/proxqp/dense/preconditioner/ruiz.hpp
include/proxsuite/proxqp/dense/solver.hpp
include/proxsuite/proxqp/dense/utils.hpp
include/proxsuite/proxqp/settings.hpp
test/src/dense_qp_eq.cpp
test/src/sparse_ruiz_equilibration.cpp

Add a setting option for solving more efficiently Linear Programs with ProxQP, as suggested by #173 (i.e., all linear algebra operations involving the Hessian cost are avoided).
This PR adds this feature for ProxQP dense backend. It will be added later for ProxQP sparse backend as well.

Add dense LP interface

---

.github/workflows/ci-linux-osx-win-conda.yml
.github/workflows/ci-linux-ros.yml
.github/workflows/ci-osx-arm64-conda.yml
.github/workflows/release-linux.yml
.github/workflows/release-osx-win.yml

This PR adds an additional job to every one of our pipelines that is called "check-_name-of-yml-file_". This job is dependent on all jobs created by the matrix (os, std, compile-mode), and only passes if all of them pass. 
This is very useful for auto-merge, as we can add only the 5 "check-_name-of-yml-file_" jobs to the branch protection rules. And it will still work, even though we change the name of the jobs (by adding more stuff to the matrix for example).

ci check all jobs pass

---

CMakeLists.txt
README.md
benchmark/CMakeLists.txt
benchmark/timings-dense-backend.cpp
benchmark/timings-diagonal-hessian.cpp
benchmark/timings-lp.cpp
bindings/python/src/expose-qpobject.hpp
bindings/python/src/expose-settings.hpp
doc/2-PROXQP_API/2-ProxQP_api.md
examples/cpp/loading_dense_qp_with_different_backend_choice.cpp
examples/python/loading_dense_qp_with_different_backend_choice.py
examples/python/solve_dense_lp.py
include/proxsuite/linalg/dense/ldlt.hpp
include/proxsuite/proxqp/dense/helpers.hpp
include/proxsuite/proxqp/dense/linesearch.hpp
include/proxsuite/proxqp/dense/preconditioner/ruiz.hpp
include/proxsuite/proxqp/dense/solver.hpp
include/proxsuite/proxqp/dense/utils.hpp
include/proxsuite/proxqp/dense/workspace.hpp
include/proxsuite/proxqp/dense/wrapper.hpp
include/proxsuite/proxqp/results.hpp
include/proxsuite/proxqp/settings.hpp
test/src/dense_maros_meszaros.cpp
test/src/dense_qp_eq.cpp
test/src/sparse_ruiz_equilibration.cpp

Adds a new backend (named PrimalLdl) for solving quicker QPs with far more constraints than primal variables (the current one is named PrimalDualLdl).
As a benchmark I get on randomly generated problems on my machine (11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz):
```
dim: 100 n_eq: 200 n_in: 200 box: 100
timings QP PrimalLdl backend : 	3.45787ms
timings QP PrimalDualLdl:       3.83495ms
timings QP Automatic : 	        3.2373ms
dim: 200 n_eq: 400 n_in: 400 box: 200
timings QP PrimalLdl backend : 	18.2621ms
timings QP PrimalDualLdl:       24.4886ms
timings QP Automatic: 	        18.4161ms
dim: 300 n_eq: 600 n_in: 600 box: 300
timings QP PrimalLdl backend : 	51.3537ms
timings QP PrimalDualLdl: 	69.2859ms
timings QP Automatic: 	        51.7177ms
dim: 400 n_eq: 800 n_in: 800 box: 400 …
```

Improve dense backend and simplify calculus when using a Diagonal Hessian

---

include/proxsuite/proxqp/dense/model.hpp
include/proxsuite/proxqp/dense/solver.hpp

this PR adds some information that is useful to debug
1) currently, there is an assert for `model.isValid()`, but it's not possible to directly see which part of the model caused the failure
2) If the Hessian type is defined as diagonal, check that it is actually the case

More information in debug mode

---

include/proxsuite/proxqp/dense/utils.hpp

Fix the typo pointed out in #254 when using a relative stopping criterion and box constraints with ProxQP dense backend.
The relative value follows the same formula as proposed in the [OSQP paper ](https://web.stanford.edu/~boyd/papers/pdf/osqp.pdf)(page 14 of the "unscalled termination criteria" paragraph).

Fix typo #254 

---

include/proxsuite/proxqp/dense/helpers.hpp
include/proxsuite/proxqp/dense/model.hpp
include/proxsuite/proxqp/sparse/helpers.hpp
test/src/dense_qp_wrapper.cpp

We are checking if H is symmetric, currently up to a precision of 0.0. This is too strict and causes problems, see #271.

Check model is_valid up to eps

---

bindings/python/proxsuite/torch/qplayer.py

Fixes issue https://github.com/Simple-Robotics/proxsuite/issues/296:
- Handles CPU/GPU transfer in `QPFunctionFn`'s `backward` function.
- Replaces `torch.Tensor` by either `torch.tensor` or `torch.empty`.

Handles CPU/GPU transfer in QPFunctionFn's backward function

---

CHANGELOG.md
test/src/dense_qp_wrapper.py

When updating scipy from 1.11.4 to 1.12.0,  `DenseqpWrapper.test_case_update_A_for_different_initial_guess` break.
It appears the test was passing only by luck. `b` was not regenerated with the new `A` matrix.
Solving `Ax=b` can then be impossible to solve.

Fix broken unit tests with scipy 1.12

---

CHANGELOG.md
bindings/python/proxsuite/torch/qplayer.py

For  `QPFunction`, we accept a parameter called `structural_feasibility` which defaults to `True`. Based on this, we will either use the class `QPFunctionFn` or `QPFunctionFn_infeas` with their corresponding `forward` and `backward` methods. 
If we decide, that the QPs to solve are structurally feasible, it is consistent to set `primal_infeasibility_solving` to `False`.

Set `primal_infeasibility_solving` to False for feasible forward in `QPFunction`

---

CHANGELOG.md
bindings/python/proxsuite/torch/qplayer.py
bindings/python/proxsuite/torch/utils.py
examples/python/qplayer_sudoku.py

following #297, where we started to replace `torch.Tensor`.
The PyTorch doc says: [torch.Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor) is an alias for the default tensor type (torch.FloatTensor).
For the rest of the tensors, we called either `.double()` or set `dtype=torch.64`. This is necessary, as these tensors contain the QP data which is passed to the proxsuite c++ bindings in `forward` and `backward` which are using the Scalar type double.

Replace torch.Tensor and fix handling of batched ineq. constraints in QPlayer

---

bindings/python/CMakeLists.txt

Add the ABI tag (“.cpython-39-x86_64-linux-gnu.so”) to Python bindings.
This is mandatory for PyPy interpreter.
Also, generate Python bindings in the right directory on Windows.

Fix python abi tag

---

CHANGELOG.md
include/proxsuite/fwd.hpp

I was getting a compilation error due to a missing `#include <cassert>`. I added it to the fwd.hpp file which fixes the issue.

include cassert in fwd.hpp

---

.github/workflows/release-linux.yml
.github/workflows/release-osx-win.yml
CHANGELOG.md

remove python 3.7 as it has reached end of life in June 2023 https://devguide.python.org/versions/

Build and release wheels for python 3.12 on all platforms

---

CHANGELOG.md
include/proxsuite/proxqp/dense/utils.hpp
include/proxsuite/proxqp/sparse/utils.hpp
test/src/dense_qp_eq.cpp
test/src/dense_qp_with_eq_and_in.cpp

we have a first check in our helper function `global_primal_residual_infeasibility` that returns if a problem is supposed to be feasible. 
I think the logic we want to check is
```
inf_norm(dy) == 0 AND infty_norm(dz) == 0
```
in this case, the problem is feasible.
However, we negate this statement as the output of the function is used to set the variable called `is_primal_infeasible`, [here](https://github.com/Simple-Robotics/proxsuite/blob/main/include/proxsuite/proxqp/dense/solver.hpp#L1028). 
If we negate the statement above, and should be replaced by OR. The fix I propose here solves the issue in #327 and proxqp returns `PROXQP_PRIMAL_INFEASIBLE` as expected.

Fix infeasibility detection logic

---

CHANGELOG.md
bindings/python/CMakeLists.txt
bindings/python/src/expose-solve.hpp
doc/2-ProxQP_api.md
doc/3-ProxQP_solve.md
doc/5-installation.md
include/proxsuite/proxqp/dense/solver.hpp
include/proxsuite/proxqp/settings.hpp
include/proxsuite/proxqp/sparse/solver.hpp

After #341, this PR aims at specifying the unit of our timings more clearly.
While preparing and testing this PR, I found issues with `cereal` on my system. As it is a head-only library, I fixed the problem by changing from `target_link_libraries` to `target_include_directories`.
After quick discussion with @Bambade, we added a hint for conda installations from source in the doc.

Specify timings in us, fix cereal, extend doc

---

CHANGELOG.md
bindings/python/CMakeLists.txt

Hi,
Here are a couple CMake fixes for installs with python bindings and where cereal and pybind11 are already available on the system.

 CMake: allow use of installed dependencies, take 2

---

CHANGELOG.md
examples/python/estimate_nonconvex_eigenvalue.py
examples/python/init_dense_qp.py
examples/python/init_dense_qp_with_box.py
examples/python/init_dense_qp_with_other_options.py
examples/python/init_dense_qp_with_timings.py
examples/python/init_with_default_options.py
examples/python/loading_sparse_qp.py
examples/python/overview-simple.py
examples/python/solve_dense_qp.py
examples/python/solve_dense_qp_with_setting.py
examples/python/solve_without_api.py
examples/python/solve_without_api_and_option.py
examples/python/update_dense_qp.py
examples/python/update_dense_qp_ws_previous_result.py
examples/python/update_sparse_qp.py
examples/python/util.py

This PR refactors a bunch of Python examples to use a function from the same `util.py` file
This helps with my draft PR #345 but should have value in itself

Refactor Python examples with a new "util.py" file

---

CHANGELOG.md
include/proxsuite/proxqp/dense/solver.hpp
test/src/dense_qp_wrapper.cpp

as pointed out in #348, there is currently a mismatch when calling the `rank_r_update`. 
I discussed it with @Bambade, and we propose this PR to fix it, and correct another typo that was found while analyzing the function. 
We also add the example from #348 as a new unittest for the  `PrimalLDLT` backend, where we trigger a `mu_update`.

Fix `mu_update` for `PrimalLDLT` backend

---

benchmark/timings-parallel.py
bindings/python/src/expose-solve.hpp

Addresses https://github.com/Simple-Robotics/proxsuite/issues/358.
Releases the Global Interpreter Lock (GIL) when using `proxsuite.proxqp.dense.solve` so python users can easily parallelize solving problems across cores. Quadprog and OSQP already do something similar.
This enables 2x or more faster parallel solving compared to using `proxsuite.proxqp.dense.VectorQP()` and `solve_in_parallel`.
On my M2 Mac, I see the following:
```
python ../benchmark/timings-parallel.py
Problem specs: n=1000 n_eq=200 n_in=200. Generating 64 such problems.
Generated problems. Solving 64 problems with 11 threads.
...
setup_vector_of_qps: 4655.346ms
setup_vector_and_solve_parallel_heuristics_threads: 5850.690ms
solve_serial_dense: 4716.554ms
solve_parallel_dense: 1934.598ms
```
Headline result is that …

Release GIL when doing standalone solves

---

.github/workflows/ci-linux-osx-win-conda.yml
.github/workflows/gh-pages.yml
.github/workflows/release-osx-win.yml
CHANGELOG.md
benchmark/timings-parallel.py
bindings/python/src/expose-solve.hpp

same PR as https://github.com/Simple-Robotics/proxsuite/pull/359. I am sorry I did a bad command while trying to run the CI on the original PR by @jberg5.

[reopen2] Release GIL when doing standalone solves

---

.github/workflows/release-linux.yml
.github/workflows/release-osx-win.yml
CHANGELOG.md

Hi,
I think we would need some python 3.13 release on PyPI.
While here, I updated a few other things in the release workflows.
Also, the PYPI_TOKEN should be removed in favor of then new "Trusted Publisher Management": https://pypi.org/manage/project/proxsuite/settings/publishing/

release: updates

---

.github/workflows/ci-linux-osx-win-conda.yml
.github/workflows/conda/environment.yml
CHANGELOG.md
include/proxsuite/linalg/veg/internal/macros.hpp

Fix https://github.com/Simple-Robotics/proxsuite/issues/367
Cl compiler doesn't expand `__VA_ARGS__` like clang or gcc. It's well [documented](https://learn.microsoft.com/en-us/cpp/preprocessor/variadic-macros?view=msvc-170) but hard to catch.
@aescande have introduce the `__VEG_PP_ID` macro to overcome this issue without activating the [/Zc:preprocessor](https://learn.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-170) compiler flags.

Fix build with Cl and C++20

---

.github/workflows/ci-arch.yml
.github/workflows/ci-linux-osx-win-conda.yml
.github/workflows/ci-linux-ros.yml
.github/workflows/release-linux.yml
.github/workflows/release-osx-win.yml

Use new github action image to build PyPI aarch wheels.
Also:
- Cancel old workflow when a new one is triggered
- Deactivate fail fast
- Test wheels on Linux

Fix pypi aarch workflow

---

CHANGELOG.md
include/proxsuite/linalg/veg/tuple.hpp

Clang 19 now requires the list of template arguments after a `template` keyword prefixing a name. This applies to the `cat::template ...` static function call in tuple.hpp.
Related: https://github.com/llvm/llvm-project/commit/f46d1463b835560d90ad3ac02b63c771e4ebe566, https://github.com/tstack/lnav/issues/1328

Fix an arcane bug on clang 19

---

.gersemirc
.git-blame-ignore-revs
.pre-commit-config.yaml
CHANGELOG.md
CMakeLists.txt
bindings/python/CMakeLists.txt
cmake-external/FindMatio.cmake
cmake-external/FindSphinx.cmake
cmake-external/compiler_warnings.cmake
cmake-external/doctest.cmake
cmake-external/doctestAddTests.cmake
cmake-external/extra_local_settings.cmake
cmake-external/sanitizers.cmake
cmake-external/static_analyzers.cmake
examples/CMakeLists.txt
examples/cpp/CMakeLists.txt
examples/julia/CMakeLists.txt
examples/python/CMakeLists.txt
test/CMakeLists.txt

Change CMake listfile formatting to gersemi

---

CHANGELOG.md
bindings/python/proxsuite/torch/qplayer.py

In Python it is better to compare to ~~not~~ _None_ (typo fixed, thanks @nim65s) with `is` or `is not` rather than `==` and `!=` (e.g. the comparison operators may not be defined).
In this code it changes nothing, because tensors are from PyTorch:
```py
In [1]: import torch
In [2]: x = torch.tensor([1, 2, 3])
In [3]: x is not None
Out[3]: True
In [4]: x != None
Out[4]: True
```
But with NumPy arrays it would yield, for instance:
```py
In [1]: x = np.array([1, 2, 3])
In [2]: x is not None
Out[2]: True
In [3]: x != None
Out[3]: array([ True,  True,  True])
In [4]: if x != None:
...:     pass
...: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 if x != None:
2 …
```

Replace `!= None` with `is not None` in Python bindings

---

.pre-commit-config.yaml
CHANGELOG.md
benchmark/timings-parallel.py
bindings/python/proxsuite/__init__.py
bindings/python/proxsuite/torch/__init__.py
bindings/python/proxsuite/torch/qplayer.py
examples/python/init_dense_qp.py
examples/python/init_dense_qp_with_box.py
examples/python/init_dense_qp_with_other_options.py
examples/python/init_dense_qp_with_timings.py
examples/python/init_with_default_options.py
examples/python/loading_sparse_qp.py
examples/python/overview-simple.py
examples/python/qplayer_sudoku.py
examples/python/solve_dense_qp.py
examples/python/solve_dense_qp_with_setting.py
examples/python/solve_without_api.py
examples/python/solve_without_api_and_option.py
examples/python/update_dense_qp_ws_previous_result.py
examples/python/update_sparse_qp.py
examples/python/util.py
pyproject.toml
test/src/dense_qp_solve.py
test/src/dense_qp_wrapper.py
test/src/parallel_qp_solve.py
test/src/sparse_qp_solve.py
test/src/sparse_qp_wrapper.py

black -> ruff

---

CHANGELOG.md
include/proxsuite/linalg/veg/type_traits/constructible.hpp

Visual studio 17.13 stop on an internal compiler error when building `veg/tuple.hpp`.
This patch add a workaround to allow to build.

Fix Visual Studio 17.13 build
